#!/usr/bin/env python
# encoding: utf-8
"""

Created by Preston Holmes on 2009-07-22.
preston@ptone.com
Copyright (c) 2009

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Verbs:
delete <t/k>
rename <t/k> new_name
remove <t/k> [k]
swap old new
combine item1 item2 [itemN...] new_name | item_pattern* new_name
bundle item1 item2 [itemN...] bundle_name
checkin
    [update]
    list
    all
    <transcript>
get
    size
    transcripts
    command
sort <t>
"""


import sys
import os
from optparse import OptionParser,OptionGroup
import radutil

def delete (t_k):
    radutil.delete(t_k)
    print '%s moved to trash' % t_k

def undelete (t_k):
    radutil.undelete(t_k)
    print '%s restored from trash' % t_k
    
def rename (old,new):
    radutil.rename(old,new)
    print '%s renamed' % old
    
def remove():
    pass
    
def swap():
    pass
    
def combine(*args):
    tlist = args[:-1]
    radutil.combine(tlist,args[-1])
    
vocab = {
    'delete':(delete,['direct']),
    'undelete':(undelete,['direct']),
    'rename':(rename,['direct','new_name']),
    'remove':(remove,['direct'],['command_file']),
    'swap':(swap,['old','new']),
    'combine':(combine,['args'])
    
}

def main(argv=None):
    parser = OptionParser()
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose",
                      help="display all verbose output",default=False)
    # parse options: metavar, default action: store
    parser.usage = """
        help message
    """
    (options, args) = parser.parse_args()
#    if options.some_option != desired_value:
#        parser.error("specified option bad")
    
    # verb needs to be first arg
    bits = args
    verb = args[0]
    del(args[0])
    if verb in vocab:
        vocab[verb][0](*tuple(args))
    else:
        parser.error('%s verb not understood' % verb)
        
if __name__ == "__main__":
    sys.exit(main())
